"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useState } from "react";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <html lang="en">
      <head>
        {/* Global metadata or other head tags can go here */}
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>DewFresh</title>
        {/* You can add any global font or other stylesheets here */}
      </head>
      <body>
    <div>
      <header className="bg-green-500 p-4 text-white">
        <div className="container mx-auto flex justify-between items-center">
          <Link href="/" className="text-6xl font-bold">
            Dewfresh
          </Link>
          <nav>
            <ul className={`sm:flex ${isMenuOpen ? 'block' : 'hidden'}`}>
        <li>
          <Link href="/" className="block px-4 py-2">Home</Link>
        </li>
        <li>
          <Link href="/about" className="block px-4 py-2">About</Link>
        </li>
        <li>
          <Link href="/contact" className="block px-4 py-2">Contact</Link>
        </li>
        <li>
          <Link href="/more" className="block px-4 py-2">More</Link>
        </li>
            </ul>
            <button
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              className="sm:hidden text-white px-4 py-2"
            >
              {isMenuOpen ? 'Close' : 'Menu'}
            </button>
          </nav>
        </div>
      </header>

      <main className="container mx-auto my-8">{children}</main>

      <footer className="bg-gray-800 text-white py-4">
        <div className="text-center">© 2024 Juice Store. All Rights Reserved.</div>
      </footer>
    </div>
    </body>
    </html>
  );
};

export default RootLayout;